import NewForm from "@/component/NewForm";
import React from "react";
import Head from "next/head";
import Link from "next/link";

const Form = () => {
  return (
    <>
      <Head>
        <title>write:here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
        ></link>
        <link rel="icon" href="/logo3.png" />
      </Head>
      <main>
        <div className="header"><Link href={"/"}><img src="/logo.svg" className="header-logo"></img></Link></div>
        <div className="container">
          <NewForm></NewForm>
        </div>
      </main>
    </>
  );
};

export default Form;
