import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { useState } from "react";
export default function Home() {
 

    async function getParsedText (file:string){
      const response = await fetch("/api/vision",{
        method:"POST",
        body: JSON.stringify(file),
      });
      if(!response.ok){
        throw new Error(response.statusText);
      }
      return await response.json();
    }
  return (
    <>
      <Head>
        <title>Write:Here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'></link>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"></link>
        <link rel="icon" href="/logo3.png" />
      </Head>
      <main>
        <div className="container center-screen">
        <div className="img-fluid">
          <img className="logo" src="/logo.svg"/>
        </div>
        <div className="welcome">
          <h2>would you like to upload a picture or take a photo?</h2>
        </div>
        <div className="container-fluid buttons">
          <Link href={"/uploadphoto"}><button type="button" className="btns btn-upload"><i className="bi bi-upload"></i></button></Link>
          <Link href={"/takephoto"}><button type="button" className="btns btn-take"><i className="bi bi-camera"></i></button></Link>
        </div>
        </div>
      </main>
    </>
  );
}
