import Head from "next/head";
import { Inter } from "@next/font/google";

export default function Home() {


    async function getParsedText (file:string){
      const response = await fetch("/api/vision",{
        method:"POST",
        body: JSON.stringify(file),
      });
      if(!response.ok){
        throw new Error(response.statusText);
      }
      return await response.json();
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <div className="header">
          <p>Write:here</p>
          <button onClick={()=>getParsedText}>
            Push me to test API endpoint
          </button>
        </div>
      </main>
    </>
  );
}
