import React from "react";
import Head from "next/head";

const Success = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
        ></link>
        <link rel="icon" href="/logo3.png" />
      </Head>
      <main>
        <div className="header">
          <img src="/logo.svg" className="header-logo"></img>
        </div>
        <div className="container center-screen">
          <div className="success-checkmark">
            <div className="check-icon">
              <span className="icon-line line-tip"></span>
              <span className="icon-line line-long"></span>
              <div className="icon-circle"></div>
              <div className="icon-fix"></div>
            </div>
          </div>
          <div className="success-message">
            <h1 className="success">success!</h1>
            <h5>email sent to:</h5>
            <h5>{localStorage.getItem("to_email")}</h5>
          </div>
        </div>
      </main>
    </>
  );
};

export default Success;
