import Head from "next/head";
import { Inter } from "@next/font/google";
import React, {
  useState,
  useEffect,
  useReducer,
  useRef,
  useCallback,
} from "react";
import Webcam from "react-webcam";
import Link from "next/link";

export default function Home() {
  const [parsedText, setParsedText] = useState("write:here");
  const [imgSrc, setImgSrc] = React.useState("");
  const webcamRef: any = React.useRef();
  const capture = useCallback(() => {
    if (webcamRef && webcamRef.current) {
      const tempSrc = webcamRef.current.getScreenshot();


      setImgSrc(tempSrc);
      getParsedText(tempSrc);
    }
  }, [webcamRef, setImgSrc]);

  async function getParsedText(file: any) {
    const index = file.indexOf(",") + 1;
    const imgData = file.substring(index);
    
    const response = await fetch("/api/vision", {
      method: "POST",
      body: JSON.stringify(imgData),
    });
    if (!response.ok) {
      throw new Error(response.statusText);
    }
    const data = await response.json();
    setParsedText(data.detections[0].description);
  }

  const videoConstraints = {
    facingMode: { exact: "environment" },
  };

  return (
    <>
      <Head>
        <title>Take Photo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <p>{parsedText}</p>
          
          <Webcam audio={false} screenshotFormat="image/jpeg" ref={webcamRef} mirrored = {false}/>
          <button className="btn btn-info" onClick={capture}>
            Take photo
          </button>
          {
            //this code displays the img once taken, change as yall ui ppl see fit. 
          imgSrc && <img src={imgSrc} />} 
        </div>
      </main>
    </>
  );
}
